version: "3.8"

services:
  postgres:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: pawguardian
      POSTGRES_DB: pawguardian
      POSTGRES_PASSWORD: pawguardian
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    networks:
      - database-network
    deploy:
      placement:
        constraints: [node.role == manager]
      endpoint_mode: vip
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pawguardian -d pawguardian" ]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 30s

  mongodb:
    image: mongo:7
    volumes:
      - mongo-vol:/data/db
    networks:
      - database-network
    deploy:
      placement:
        constraints: [node.role == manager]

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pawguardian.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - database-network
    deploy:
      placement:
        constraints: [ node.role == manager ]
    ports:
      - target: 80
        published: 5050
        protocol: tcp
        mode: host

  backend:
    image: daniptrk/pawguardian-backend:latest
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/pawguardian
      DB_USERNAME: pawguardian
      DB_PASSWORD: pawguardian
      SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT: -1
      SPRING_FLYWAY_CONNECT_RETRIES: 10
      SPRING_FLYWAY_CONNECT_RETRIES_INTERVAL: 10
    networks:
      - backend-network
      - database-network
    deploy:
      replicas: 2
      placement:
        constraints: [ node.role == manager ]  # manager for testing
        max_replicas_per_node: 2
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 10 
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
    ports:
      - target: 8090
        published: 8090
        protocol: tcp
        mode: ingress

volumes:
  postgres-vol:
  mongo-vol:

networks:
  database-network:
    driver: overlay
    attachable: true
  backend-network:
    driver: overlay
    attachable: true
