/* tslint:disable */
/* eslint-disable */
/**
 * PawGuardian API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiResponseDto
 */
export interface ApiResponseDto {
    /**
     * 
     * @type {number}
     * @memberof ApiResponseDto
     */
    statusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseDto
     */
    message?: string;
    /**
     * 
     * @type {Date}
     * @memberof ApiResponseDto
     */
    timestamp?: Date;
}

/**
 * Check if a given object implements the ApiResponseDto interface.
 */
export function instanceOfApiResponseDto(value: object): value is ApiResponseDto {
    return true;
}

export function ApiResponseDtoFromJSON(json: any): ApiResponseDto {
    return ApiResponseDtoFromJSONTyped(json, false);
}

export function ApiResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['status_code'] == null ? undefined : json['status_code'],
        'message': json['message'] == null ? undefined : json['message'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
    };
}

export function ApiResponseDtoToJSON(json: any): ApiResponseDto {
    return ApiResponseDtoToJSONTyped(json, false);
}

export function ApiResponseDtoToJSONTyped(value?: ApiResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_code': value['statusCode'],
        'message': value['message'],
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
    };
}

