/* tslint:disable */
/* eslint-disable */
/**
 * PawGuardian API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeviceResponseDto
 */
export interface DeviceResponseDto {
    /**
     * 
     * @type {number}
     * @memberof DeviceResponseDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DeviceResponseDto
     */
    serialNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceResponseDto
     */
    model?: string;
    /**
     * 
     * @type {number}
     * @memberof DeviceResponseDto
     */
    batteryLevel?: number;
    /**
     * 
     * @type {number}
     * @memberof DeviceResponseDto
     */
    petId?: number;
    /**
     * 
     * @type {string}
     * @memberof DeviceResponseDto
     */
    petName?: string;
}

/**
 * Check if a given object implements the DeviceResponseDto interface.
 */
export function instanceOfDeviceResponseDto(value: object): value is DeviceResponseDto {
    return true;
}

export function DeviceResponseDtoFromJSON(json: any): DeviceResponseDto {
    return DeviceResponseDtoFromJSONTyped(json, false);
}

export function DeviceResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'serialNumber': json['serialNumber'] == null ? undefined : json['serialNumber'],
        'model': json['model'] == null ? undefined : json['model'],
        'batteryLevel': json['batteryLevel'] == null ? undefined : json['batteryLevel'],
        'petId': json['petId'] == null ? undefined : json['petId'],
        'petName': json['petName'] == null ? undefined : json['petName'],
    };
}

export function DeviceResponseDtoToJSON(json: any): DeviceResponseDto {
    return DeviceResponseDtoToJSONTyped(json, false);
}

export function DeviceResponseDtoToJSONTyped(value?: DeviceResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'serialNumber': value['serialNumber'],
        'model': value['model'],
        'batteryLevel': value['batteryLevel'],
        'petId': value['petId'],
        'petName': value['petName'],
    };
}

