/* tslint:disable */
/* eslint-disable */
/**
 * PawGuardian API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeviceRequestDto
 */
export interface DeviceRequestDto {
    /**
     * 
     * @type {string}
     * @memberof DeviceRequestDto
     */
    serialNumber: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceRequestDto
     */
    model: string;
    /**
     * 
     * @type {number}
     * @memberof DeviceRequestDto
     */
    petId: number;
}

/**
 * Check if a given object implements the DeviceRequestDto interface.
 */
export function instanceOfDeviceRequestDto(value: object): value is DeviceRequestDto {
    if (!('serialNumber' in value) || value['serialNumber'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('petId' in value) || value['petId'] === undefined) return false;
    return true;
}

export function DeviceRequestDtoFromJSON(json: any): DeviceRequestDto {
    return DeviceRequestDtoFromJSONTyped(json, false);
}

export function DeviceRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'serialNumber': json['serialNumber'],
        'model': json['model'],
        'petId': json['petId'],
    };
}

export function DeviceRequestDtoToJSON(json: any): DeviceRequestDto {
    return DeviceRequestDtoToJSONTyped(json, false);
}

export function DeviceRequestDtoToJSONTyped(value?: DeviceRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serialNumber': value['serialNumber'],
        'model': value['model'],
        'petId': value['petId'],
    };
}

