/* tslint:disable */
/* eslint-disable */
/**
 * PawGuardian API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeedbackResponseDto
 */
export interface FeedbackResponseDto {
    /**
     * 
     * @type {number}
     * @memberof FeedbackResponseDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FeedbackResponseDto
     */
    userEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackResponseDto
     */
    category?: string;
    /**
     * 
     * @type {number}
     * @memberof FeedbackResponseDto
     */
    rating?: number;
    /**
     * 
     * @type {boolean}
     * @memberof FeedbackResponseDto
     */
    subscribe?: boolean;
    /**
     * 
     * @type {string}
     * @memberof FeedbackResponseDto
     */
    message?: string;
    /**
     * 
     * @type {Date}
     * @memberof FeedbackResponseDto
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the FeedbackResponseDto interface.
 */
export function instanceOfFeedbackResponseDto(value: object): value is FeedbackResponseDto {
    return true;
}

export function FeedbackResponseDtoFromJSON(json: any): FeedbackResponseDto {
    return FeedbackResponseDtoFromJSONTyped(json, false);
}

export function FeedbackResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userEmail': json['userEmail'] == null ? undefined : json['userEmail'],
        'category': json['category'] == null ? undefined : json['category'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'subscribe': json['subscribe'] == null ? undefined : json['subscribe'],
        'message': json['message'] == null ? undefined : json['message'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function FeedbackResponseDtoToJSON(json: any): FeedbackResponseDto {
    return FeedbackResponseDtoToJSONTyped(json, false);
}

export function FeedbackResponseDtoToJSONTyped(value?: FeedbackResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userEmail': value['userEmail'],
        'category': value['category'],
        'rating': value['rating'],
        'subscribe': value['subscribe'],
        'message': value['message'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

