/* tslint:disable */
/* eslint-disable */
/**
 * PawGuardian API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeedbackRequestDto
 */
export interface FeedbackRequestDto {
    /**
     * 
     * @type {string}
     * @memberof FeedbackRequestDto
     */
    category: string;
    /**
     * 
     * @type {number}
     * @memberof FeedbackRequestDto
     */
    rating: number;
    /**
     * 
     * @type {boolean}
     * @memberof FeedbackRequestDto
     */
    subscribe?: boolean;
    /**
     * 
     * @type {string}
     * @memberof FeedbackRequestDto
     */
    message: string;
}

/**
 * Check if a given object implements the FeedbackRequestDto interface.
 */
export function instanceOfFeedbackRequestDto(value: object): value is FeedbackRequestDto {
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function FeedbackRequestDtoFromJSON(json: any): FeedbackRequestDto {
    return FeedbackRequestDtoFromJSONTyped(json, false);
}

export function FeedbackRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'],
        'rating': json['rating'],
        'subscribe': json['subscribe'] == null ? undefined : json['subscribe'],
        'message': json['message'],
    };
}

export function FeedbackRequestDtoToJSON(json: any): FeedbackRequestDto {
    return FeedbackRequestDtoToJSONTyped(json, false);
}

export function FeedbackRequestDtoToJSONTyped(value?: FeedbackRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': value['category'],
        'rating': value['rating'],
        'subscribe': value['subscribe'],
        'message': value['message'],
    };
}

