/* tslint:disable */
/* eslint-disable */
/**
 * PawGuardian API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeofenceCheckResponseDto
 */
export interface GeofenceCheckResponseDto {
    /**
     * 
     * @type {number}
     * @memberof GeofenceCheckResponseDto
     */
    petId?: number;
    /**
     * 
     * @type {string}
     * @memberof GeofenceCheckResponseDto
     */
    petName?: string;
    /**
     * 
     * @type {number}
     * @memberof GeofenceCheckResponseDto
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof GeofenceCheckResponseDto
     */
    longitude?: number;
    /**
     * 
     * @type {boolean}
     * @memberof GeofenceCheckResponseDto
     */
    insideSafeZone?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GeofenceCheckResponseDto
     */
    safeZoneName?: string;
    /**
     * 
     * @type {string}
     * @memberof GeofenceCheckResponseDto
     */
    message?: string;
}

/**
 * Check if a given object implements the GeofenceCheckResponseDto interface.
 */
export function instanceOfGeofenceCheckResponseDto(value: object): value is GeofenceCheckResponseDto {
    return true;
}

export function GeofenceCheckResponseDtoFromJSON(json: any): GeofenceCheckResponseDto {
    return GeofenceCheckResponseDtoFromJSONTyped(json, false);
}

export function GeofenceCheckResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeofenceCheckResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'petId': json['petId'] == null ? undefined : json['petId'],
        'petName': json['petName'] == null ? undefined : json['petName'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'insideSafeZone': json['insideSafeZone'] == null ? undefined : json['insideSafeZone'],
        'safeZoneName': json['safeZoneName'] == null ? undefined : json['safeZoneName'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function GeofenceCheckResponseDtoToJSON(json: any): GeofenceCheckResponseDto {
    return GeofenceCheckResponseDtoToJSONTyped(json, false);
}

export function GeofenceCheckResponseDtoToJSONTyped(value?: GeofenceCheckResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'petId': value['petId'],
        'petName': value['petName'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'insideSafeZone': value['insideSafeZone'],
        'safeZoneName': value['safeZoneName'],
        'message': value['message'],
    };
}

