/* tslint:disable */
/* eslint-disable */
/**
 * PawGuardian API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeofenceCheckRequestDto
 */
export interface GeofenceCheckRequestDto {
    /**
     * 
     * @type {number}
     * @memberof GeofenceCheckRequestDto
     */
    latitude: number;
    /**
     * 
     * @type {number}
     * @memberof GeofenceCheckRequestDto
     */
    longitude: number;
}

/**
 * Check if a given object implements the GeofenceCheckRequestDto interface.
 */
export function instanceOfGeofenceCheckRequestDto(value: object): value is GeofenceCheckRequestDto {
    if (!('latitude' in value) || value['latitude'] === undefined) return false;
    if (!('longitude' in value) || value['longitude'] === undefined) return false;
    return true;
}

export function GeofenceCheckRequestDtoFromJSON(json: any): GeofenceCheckRequestDto {
    return GeofenceCheckRequestDtoFromJSONTyped(json, false);
}

export function GeofenceCheckRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeofenceCheckRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'latitude': json['latitude'],
        'longitude': json['longitude'],
    };
}

export function GeofenceCheckRequestDtoToJSON(json: any): GeofenceCheckRequestDto {
    return GeofenceCheckRequestDtoToJSONTyped(json, false);
}

export function GeofenceCheckRequestDtoToJSONTyped(value?: GeofenceCheckRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'latitude': value['latitude'],
        'longitude': value['longitude'],
    };
}

