/* tslint:disable */
/* eslint-disable */
/**
 * PawGuardian API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthMetricDto
 */
export interface HealthMetricDto {
    /**
     * 
     * @type {number}
     * @memberof HealthMetricDto
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof HealthMetricDto
     */
    petId: number;
    /**
     * 
     * @type {number}
     * @memberof HealthMetricDto
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof HealthMetricDto
     */
    longitude?: number;
    /**
     * 
     * @type {number}
     * @memberof HealthMetricDto
     */
    heartRate?: number;
    /**
     * 
     * @type {number}
     * @memberof HealthMetricDto
     */
    temperature?: number;
    /**
     * 
     * @type {number}
     * @memberof HealthMetricDto
     */
    batteryLevel?: number;
    /**
     * 
     * @type {Date}
     * @memberof HealthMetricDto
     */
    timestamp?: Date;
}

/**
 * Check if a given object implements the HealthMetricDto interface.
 */
export function instanceOfHealthMetricDto(value: object): value is HealthMetricDto {
    if (!('petId' in value) || value['petId'] === undefined) return false;
    return true;
}

export function HealthMetricDtoFromJSON(json: any): HealthMetricDto {
    return HealthMetricDtoFromJSONTyped(json, false);
}

export function HealthMetricDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthMetricDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'petId': json['petId'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'heartRate': json['heartRate'] == null ? undefined : json['heartRate'],
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
        'batteryLevel': json['batteryLevel'] == null ? undefined : json['batteryLevel'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
    };
}

export function HealthMetricDtoToJSON(json: any): HealthMetricDto {
    return HealthMetricDtoToJSONTyped(json, false);
}

export function HealthMetricDtoToJSONTyped(value?: HealthMetricDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'petId': value['petId'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'heartRate': value['heartRate'],
        'temperature': value['temperature'],
        'batteryLevel': value['batteryLevel'],
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
    };
}

