/* tslint:disable */
/* eslint-disable */
/**
 * PawGuardian API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PetRequestDto
 */
export interface PetRequestDto {
    /**
     * 
     * @type {string}
     * @memberof PetRequestDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PetRequestDto
     */
    species: string;
    /**
     * 
     * @type {string}
     * @memberof PetRequestDto
     */
    breed?: string;
    /**
     * 
     * @type {number}
     * @memberof PetRequestDto
     */
    age: number;
}

/**
 * Check if a given object implements the PetRequestDto interface.
 */
export function instanceOfPetRequestDto(value: object): value is PetRequestDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('species' in value) || value['species'] === undefined) return false;
    if (!('age' in value) || value['age'] === undefined) return false;
    return true;
}

export function PetRequestDtoFromJSON(json: any): PetRequestDto {
    return PetRequestDtoFromJSONTyped(json, false);
}

export function PetRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PetRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'species': json['species'],
        'breed': json['breed'] == null ? undefined : json['breed'],
        'age': json['age'],
    };
}

export function PetRequestDtoToJSON(json: any): PetRequestDto {
    return PetRequestDtoToJSONTyped(json, false);
}

export function PetRequestDtoToJSONTyped(value?: PetRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'species': value['species'],
        'breed': value['breed'],
        'age': value['age'],
    };
}

