/* tslint:disable */
/* eslint-disable */
/**
 * PawGuardian API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PetResponseDto
 */
export interface PetResponseDto {
    /**
     * 
     * @type {number}
     * @memberof PetResponseDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PetResponseDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PetResponseDto
     */
    species?: string;
    /**
     * 
     * @type {string}
     * @memberof PetResponseDto
     */
    breed?: string;
    /**
     * 
     * @type {number}
     * @memberof PetResponseDto
     */
    age?: number;
    /**
     * 
     * @type {string}
     * @memberof PetResponseDto
     */
    ownerEmail?: string;
    /**
     * 
     * @type {Set<number>}
     * @memberof PetResponseDto
     */
    assignedVetIds?: Set<number>;
}

/**
 * Check if a given object implements the PetResponseDto interface.
 */
export function instanceOfPetResponseDto(value: object): value is PetResponseDto {
    return true;
}

export function PetResponseDtoFromJSON(json: any): PetResponseDto {
    return PetResponseDtoFromJSONTyped(json, false);
}

export function PetResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PetResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'species': json['species'] == null ? undefined : json['species'],
        'breed': json['breed'] == null ? undefined : json['breed'],
        'age': json['age'] == null ? undefined : json['age'],
        'ownerEmail': json['ownerEmail'] == null ? undefined : json['ownerEmail'],
        'assignedVetIds': json['assignedVetIds'] == null ? undefined : new Set(json['assignedVetIds']),
    };
}

export function PetResponseDtoToJSON(json: any): PetResponseDto {
    return PetResponseDtoToJSONTyped(json, false);
}

export function PetResponseDtoToJSONTyped(value?: PetResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'species': value['species'],
        'breed': value['breed'],
        'age': value['age'],
        'ownerEmail': value['ownerEmail'],
        'assignedVetIds': value['assignedVetIds'] == null ? undefined : Array.from(value['assignedVetIds'] as Set<any>),
    };
}

