/* tslint:disable */
/* eslint-disable */
/**
 * PawGuardian API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PetSpecies
 */
export interface PetSpecies {
    /**
     * 
     * @type {number}
     * @memberof PetSpecies
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PetSpecies
     */
    name?: string;
}

/**
 * Check if a given object implements the PetSpecies interface.
 */
export function instanceOfPetSpecies(value: object): value is PetSpecies {
    return true;
}

export function PetSpeciesFromJSON(json: any): PetSpecies {
    return PetSpeciesFromJSONTyped(json, false);
}

export function PetSpeciesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PetSpecies {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function PetSpeciesToJSON(json: any): PetSpecies {
    return PetSpeciesToJSONTyped(json, false);
}

export function PetSpeciesToJSONTyped(value?: PetSpecies | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

