/* tslint:disable */
/* eslint-disable */
/**
 * PawGuardian API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SafeZoneVertexDto } from './SafeZoneVertexDto';
import {
    SafeZoneVertexDtoFromJSON,
    SafeZoneVertexDtoFromJSONTyped,
    SafeZoneVertexDtoToJSON,
    SafeZoneVertexDtoToJSONTyped,
} from './SafeZoneVertexDto';

/**
 * 
 * @export
 * @interface SafeZoneResponseDto
 */
export interface SafeZoneResponseDto {
    /**
     * 
     * @type {number}
     * @memberof SafeZoneResponseDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SafeZoneResponseDto
     */
    zoneName?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SafeZoneResponseDto
     */
    active?: boolean;
    /**
     * 
     * @type {number}
     * @memberof SafeZoneResponseDto
     */
    petId?: number;
    /**
     * 
     * @type {Array<SafeZoneVertexDto>}
     * @memberof SafeZoneResponseDto
     */
    vertices?: Array<SafeZoneVertexDto>;
}

/**
 * Check if a given object implements the SafeZoneResponseDto interface.
 */
export function instanceOfSafeZoneResponseDto(value: object): value is SafeZoneResponseDto {
    return true;
}

export function SafeZoneResponseDtoFromJSON(json: any): SafeZoneResponseDto {
    return SafeZoneResponseDtoFromJSONTyped(json, false);
}

export function SafeZoneResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SafeZoneResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'zoneName': json['zoneName'] == null ? undefined : json['zoneName'],
        'active': json['active'] == null ? undefined : json['active'],
        'petId': json['petId'] == null ? undefined : json['petId'],
        'vertices': json['vertices'] == null ? undefined : ((json['vertices'] as Array<any>).map(SafeZoneVertexDtoFromJSON)),
    };
}

export function SafeZoneResponseDtoToJSON(json: any): SafeZoneResponseDto {
    return SafeZoneResponseDtoToJSONTyped(json, false);
}

export function SafeZoneResponseDtoToJSONTyped(value?: SafeZoneResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'zoneName': value['zoneName'],
        'active': value['active'],
        'petId': value['petId'],
        'vertices': value['vertices'] == null ? undefined : ((value['vertices'] as Array<any>).map(SafeZoneVertexDtoToJSON)),
    };
}

