/* tslint:disable */
/* eslint-disable */
/**
 * PawGuardian API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SafeZoneVertexDto } from './SafeZoneVertexDto';
import {
    SafeZoneVertexDtoFromJSON,
    SafeZoneVertexDtoFromJSONTyped,
    SafeZoneVertexDtoToJSON,
    SafeZoneVertexDtoToJSONTyped,
} from './SafeZoneVertexDto';

/**
 * 
 * @export
 * @interface SafeZoneRequestDto
 */
export interface SafeZoneRequestDto {
    /**
     * 
     * @type {string}
     * @memberof SafeZoneRequestDto
     */
    zoneName: string;
    /**
     * 
     * @type {boolean}
     * @memberof SafeZoneRequestDto
     */
    active?: boolean;
    /**
     * 
     * @type {Array<SafeZoneVertexDto>}
     * @memberof SafeZoneRequestDto
     */
    vertices: Array<SafeZoneVertexDto>;
}

/**
 * Check if a given object implements the SafeZoneRequestDto interface.
 */
export function instanceOfSafeZoneRequestDto(value: object): value is SafeZoneRequestDto {
    if (!('zoneName' in value) || value['zoneName'] === undefined) return false;
    if (!('vertices' in value) || value['vertices'] === undefined) return false;
    return true;
}

export function SafeZoneRequestDtoFromJSON(json: any): SafeZoneRequestDto {
    return SafeZoneRequestDtoFromJSONTyped(json, false);
}

export function SafeZoneRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SafeZoneRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'zoneName': json['zoneName'],
        'active': json['active'] == null ? undefined : json['active'],
        'vertices': ((json['vertices'] as Array<any>).map(SafeZoneVertexDtoFromJSON)),
    };
}

export function SafeZoneRequestDtoToJSON(json: any): SafeZoneRequestDto {
    return SafeZoneRequestDtoToJSONTyped(json, false);
}

export function SafeZoneRequestDtoToJSONTyped(value?: SafeZoneRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'zoneName': value['zoneName'],
        'active': value['active'],
        'vertices': ((value['vertices'] as Array<any>).map(SafeZoneVertexDtoToJSON)),
    };
}

