/* tslint:disable */
/* eslint-disable */
/**
 * PawGuardian API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SafeZoneVertexDto
 */
export interface SafeZoneVertexDto {
    /**
     * 
     * @type {number}
     * @memberof SafeZoneVertexDto
     */
    latitude: number;
    /**
     * 
     * @type {number}
     * @memberof SafeZoneVertexDto
     */
    longitude: number;
}

/**
 * Check if a given object implements the SafeZoneVertexDto interface.
 */
export function instanceOfSafeZoneVertexDto(value: object): value is SafeZoneVertexDto {
    if (!('latitude' in value) || value['latitude'] === undefined) return false;
    if (!('longitude' in value) || value['longitude'] === undefined) return false;
    return true;
}

export function SafeZoneVertexDtoFromJSON(json: any): SafeZoneVertexDto {
    return SafeZoneVertexDtoFromJSONTyped(json, false);
}

export function SafeZoneVertexDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SafeZoneVertexDto {
    if (json == null) {
        return json;
    }
    return {
        
        'latitude': json['latitude'],
        'longitude': json['longitude'],
    };
}

export function SafeZoneVertexDtoToJSON(json: any): SafeZoneVertexDto {
    return SafeZoneVertexDtoToJSONTyped(json, false);
}

export function SafeZoneVertexDtoToJSONTyped(value?: SafeZoneVertexDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'latitude': value['latitude'],
        'longitude': value['longitude'],
    };
}

