/* tslint:disable */
/* eslint-disable */
/**
 * PawGuardian API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpeciesRequestDto
 */
export interface SpeciesRequestDto {
    /**
     * 
     * @type {string}
     * @memberof SpeciesRequestDto
     */
    name: string;
}

/**
 * Check if a given object implements the SpeciesRequestDto interface.
 */
export function instanceOfSpeciesRequestDto(value: object): value is SpeciesRequestDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function SpeciesRequestDtoFromJSON(json: any): SpeciesRequestDto {
    return SpeciesRequestDtoFromJSONTyped(json, false);
}

export function SpeciesRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpeciesRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function SpeciesRequestDtoToJSON(json: any): SpeciesRequestDto {
    return SpeciesRequestDtoToJSONTyped(json, false);
}

export function SpeciesRequestDtoToJSONTyped(value?: SpeciesRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

