apiVersion: v1
kind: Secret
metadata:
  name: pawguardian-secrets
  namespace: pawguardian
type: Opaque
stringData:
  # Override these via kubectl
  mail-username: ""
  mail-password: ""
  db-password: "pawguardian"

