CREATE TABLE project.devices
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    serial_number VARCHAR(255),
    model         VARCHAR(255),
    battery_level INTEGER,
    pet_id        BIGINT,
    CONSTRAINT pk_devices PRIMARY KEY (id)
);

CREATE TABLE project.health_metrics
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    heart_rate  DOUBLE PRECISION,
    temperature DOUBLE PRECISION,
    latitude    DOUBLE PRECISION,
    longitude   DOUBLE PRECISION,
    timestamp   TIMESTAMP WITHOUT TIME ZONE,
    pet_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_health_metrics PRIMARY KEY (id)
);

CREATE TABLE project.pet_species
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_pet_species PRIMARY KEY (id)
);

CREATE TABLE project.pets
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    breed      VARCHAR(255),
    age        INTEGER,
    owner_id   BIGINT                                  NOT NULL,
    species_id INTEGER                                 NOT NULL,
    CONSTRAINT pk_pets PRIMARY KEY (id)
);

CREATE TABLE project.roles
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE project.safe_zone_vertices
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    latitude       DOUBLE PRECISION,
    longitude      DOUBLE PRECISION,
    sequence_order INTEGER,
    safe_zone_id   BIGINT,
    CONSTRAINT pk_safe_zone_vertices PRIMARY KEY (id)
);

CREATE TABLE project.safe_zones
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    zone_name VARCHAR(255),
    is_active BOOLEAN                                 NOT NULL,
    pet_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_safe_zones PRIMARY KEY (id)
);

CREATE TABLE project.user_role
(
    role_id INTEGER NOT NULL,
    user_id BIGINT  NOT NULL,
    CONSTRAINT pk_user_role PRIMARY KEY (role_id, user_id)
);

CREATE TABLE project.users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    email    VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE project.devices
    ADD CONSTRAINT uc_devices_pet UNIQUE (pet_id);

ALTER TABLE project.devices
    ADD CONSTRAINT uc_devices_serialnumber UNIQUE (serial_number);

ALTER TABLE project.roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);

ALTER TABLE project.users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE project.users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE project.devices
    ADD CONSTRAINT FK_DEVICES_ON_PET FOREIGN KEY (pet_id) REFERENCES project.pets (id);

ALTER TABLE project.health_metrics
    ADD CONSTRAINT FK_HEALTH_METRICS_ON_PET FOREIGN KEY (pet_id) REFERENCES project.pets (id);

ALTER TABLE project.pets
    ADD CONSTRAINT FK_PETS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES project.users (id);

ALTER TABLE project.pets
    ADD CONSTRAINT FK_PETS_ON_SPECIES FOREIGN KEY (species_id) REFERENCES project.pet_species (id);

ALTER TABLE project.safe_zones
    ADD CONSTRAINT FK_SAFE_ZONES_ON_PET FOREIGN KEY (pet_id) REFERENCES project.pets (id);

ALTER TABLE project.safe_zone_vertices
    ADD CONSTRAINT FK_SAFE_ZONE_VERTICES_ON_SAFE_ZONE FOREIGN KEY (safe_zone_id) REFERENCES project.safe_zones (id);

ALTER TABLE project.user_role
    ADD CONSTRAINT fk_user_role_on_role FOREIGN KEY (role_id) REFERENCES project.roles (id);

ALTER TABLE project.user_role
    ADD CONSTRAINT fk_user_role_on_user FOREIGN KEY (user_id) REFERENCES project.users (id);