/* tslint:disable */
/* eslint-disable */
/**
 * PawGuardian API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiResponseDto,
  DeviceRequestDto,
  DeviceResponseDto,
} from '../models/index';
import {
    ApiResponseDtoFromJSON,
    ApiResponseDtoToJSON,
    DeviceRequestDtoFromJSON,
    DeviceRequestDtoToJSON,
    DeviceResponseDtoFromJSON,
    DeviceResponseDtoToJSON,
} from '../models/index';

export interface GetDeviceForPetRequest {
    petId: number;
}

export interface RegisterDeviceRequest {
    deviceRequestDto: DeviceRequestDto;
}

export interface RemoveDeviceRequest {
    petId: number;
}

/**
 * 
 */
export class DeviceControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for getDeviceForPet without sending the request
     */
    async getDeviceForPetRequestOpts(requestParameters: GetDeviceForPetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['petId'] == null) {
            throw new runtime.RequiredError(
                'petId',
                'Required parameter "petId" was null or undefined when calling getDeviceForPet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/devices/pet/{petId}`;
        urlPath = urlPath.replace(`{${"petId"}}`, encodeURIComponent(String(requestParameters['petId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getDeviceForPetRaw(requestParameters: GetDeviceForPetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeviceResponseDto>> {
        const requestOptions = await this.getDeviceForPetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeviceResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async getDeviceForPet(requestParameters: GetDeviceForPetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeviceResponseDto> {
        const response = await this.getDeviceForPetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMyDevices without sending the request
     */
    async getMyDevicesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/devices/my-devices`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getMyDevicesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DeviceResponseDto>>> {
        const requestOptions = await this.getMyDevicesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DeviceResponseDtoFromJSON));
    }

    /**
     */
    async getMyDevices(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DeviceResponseDto>> {
        const response = await this.getMyDevicesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for registerDevice without sending the request
     */
    async registerDeviceRequestOpts(requestParameters: RegisterDeviceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['deviceRequestDto'] == null) {
            throw new runtime.RequiredError(
                'deviceRequestDto',
                'Required parameter "deviceRequestDto" was null or undefined when calling registerDevice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/devices`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeviceRequestDtoToJSON(requestParameters['deviceRequestDto']),
        };
    }

    /**
     */
    async registerDeviceRaw(requestParameters: RegisterDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeviceResponseDto>> {
        const requestOptions = await this.registerDeviceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeviceResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async registerDevice(requestParameters: RegisterDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeviceResponseDto> {
        const response = await this.registerDeviceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for removeDevice without sending the request
     */
    async removeDeviceRequestOpts(requestParameters: RemoveDeviceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['petId'] == null) {
            throw new runtime.RequiredError(
                'petId',
                'Required parameter "petId" was null or undefined when calling removeDevice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/devices/pet/{petId}`;
        urlPath = urlPath.replace(`{${"petId"}}`, encodeURIComponent(String(requestParameters['petId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async removeDeviceRaw(requestParameters: RemoveDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseDto>> {
        const requestOptions = await this.removeDeviceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async removeDevice(requestParameters: RemoveDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseDto> {
        const response = await this.removeDeviceRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
