/* tslint:disable */
/* eslint-disable */
/**
 * PawGuardian API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiResponseDto,
  FeedbackRequestDto,
  FeedbackResponseDto,
} from '../models/index';
import {
    ApiResponseDtoFromJSON,
    ApiResponseDtoToJSON,
    FeedbackRequestDtoFromJSON,
    FeedbackRequestDtoToJSON,
    FeedbackResponseDtoFromJSON,
    FeedbackResponseDtoToJSON,
} from '../models/index';

export interface DeleteFeedbackRequest {
    id: number;
}

export interface GetFeedbackByIdRequest {
    id: number;
}

export interface SubmitFeedbackRequest {
    feedbackRequestDto: FeedbackRequestDto;
}

/**
 * 
 */
export class FeedbackControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for deleteFeedback without sending the request
     */
    async deleteFeedbackRequestOpts(requestParameters: DeleteFeedbackRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteFeedback().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/feedback/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async deleteFeedbackRaw(requestParameters: DeleteFeedbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseDto>> {
        const requestOptions = await this.deleteFeedbackRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async deleteFeedback(requestParameters: DeleteFeedbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseDto> {
        const response = await this.deleteFeedbackRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAllFeedback without sending the request
     */
    async getAllFeedbackRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/feedback`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getAllFeedbackRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FeedbackResponseDto>>> {
        const requestOptions = await this.getAllFeedbackRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FeedbackResponseDtoFromJSON));
    }

    /**
     */
    async getAllFeedback(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FeedbackResponseDto>> {
        const response = await this.getAllFeedbackRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFeedbackById without sending the request
     */
    async getFeedbackByIdRequestOpts(requestParameters: GetFeedbackByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getFeedbackById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/feedback/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getFeedbackByIdRaw(requestParameters: GetFeedbackByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FeedbackResponseDto>> {
        const requestOptions = await this.getFeedbackByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FeedbackResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async getFeedbackById(requestParameters: GetFeedbackByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FeedbackResponseDto> {
        const response = await this.getFeedbackByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for submitFeedback without sending the request
     */
    async submitFeedbackRequestOpts(requestParameters: SubmitFeedbackRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['feedbackRequestDto'] == null) {
            throw new runtime.RequiredError(
                'feedbackRequestDto',
                'Required parameter "feedbackRequestDto" was null or undefined when calling submitFeedback().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/feedback`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FeedbackRequestDtoToJSON(requestParameters['feedbackRequestDto']),
        };
    }

    /**
     */
    async submitFeedbackRaw(requestParameters: SubmitFeedbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FeedbackResponseDto>> {
        const requestOptions = await this.submitFeedbackRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FeedbackResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async submitFeedback(requestParameters: SubmitFeedbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FeedbackResponseDto> {
        const response = await this.submitFeedbackRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
