/* tslint:disable */
/* eslint-disable */
/**
 * PawGuardian API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiResponseDto,
  GeofenceCheckRequestDto,
  GeofenceCheckResponseDto,
  SafeZoneRequestDto,
  SafeZoneResponseDto,
} from '../models/index';
import {
    ApiResponseDtoFromJSON,
    ApiResponseDtoToJSON,
    GeofenceCheckRequestDtoFromJSON,
    GeofenceCheckRequestDtoToJSON,
    GeofenceCheckResponseDtoFromJSON,
    GeofenceCheckResponseDtoToJSON,
    SafeZoneRequestDtoFromJSON,
    SafeZoneRequestDtoToJSON,
    SafeZoneResponseDtoFromJSON,
    SafeZoneResponseDtoToJSON,
} from '../models/index';

export interface CheckGeofenceRequest {
    petId: number;
    geofenceCheckRequestDto: GeofenceCheckRequestDto;
}

export interface CreateSafeZoneRequest {
    petId: number;
    safeZoneRequestDto: SafeZoneRequestDto;
}

export interface DeleteSafeZoneRequest {
    petId: number;
    zoneId: number;
}

export interface GetSafeZoneById1Request {
    petId: number;
    zoneId: number;
}

export interface GetSafeZones1Request {
    petId: number;
}

export interface UpdateSafeZoneRequest {
    petId: number;
    zoneId: number;
    safeZoneRequestDto: SafeZoneRequestDto;
}

/**
 * 
 */
export class SafeZoneControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for checkGeofence without sending the request
     */
    async checkGeofenceRequestOpts(requestParameters: CheckGeofenceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['petId'] == null) {
            throw new runtime.RequiredError(
                'petId',
                'Required parameter "petId" was null or undefined when calling checkGeofence().'
            );
        }

        if (requestParameters['geofenceCheckRequestDto'] == null) {
            throw new runtime.RequiredError(
                'geofenceCheckRequestDto',
                'Required parameter "geofenceCheckRequestDto" was null or undefined when calling checkGeofence().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/pets/{petId}/safe-zones/check`;
        urlPath = urlPath.replace(`{${"petId"}}`, encodeURIComponent(String(requestParameters['petId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GeofenceCheckRequestDtoToJSON(requestParameters['geofenceCheckRequestDto']),
        };
    }

    /**
     */
    async checkGeofenceRaw(requestParameters: CheckGeofenceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GeofenceCheckResponseDto>> {
        const requestOptions = await this.checkGeofenceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GeofenceCheckResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async checkGeofence(requestParameters: CheckGeofenceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GeofenceCheckResponseDto> {
        const response = await this.checkGeofenceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createSafeZone without sending the request
     */
    async createSafeZoneRequestOpts(requestParameters: CreateSafeZoneRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['petId'] == null) {
            throw new runtime.RequiredError(
                'petId',
                'Required parameter "petId" was null or undefined when calling createSafeZone().'
            );
        }

        if (requestParameters['safeZoneRequestDto'] == null) {
            throw new runtime.RequiredError(
                'safeZoneRequestDto',
                'Required parameter "safeZoneRequestDto" was null or undefined when calling createSafeZone().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/pets/{petId}/safe-zones`;
        urlPath = urlPath.replace(`{${"petId"}}`, encodeURIComponent(String(requestParameters['petId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SafeZoneRequestDtoToJSON(requestParameters['safeZoneRequestDto']),
        };
    }

    /**
     */
    async createSafeZoneRaw(requestParameters: CreateSafeZoneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SafeZoneResponseDto>> {
        const requestOptions = await this.createSafeZoneRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SafeZoneResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async createSafeZone(requestParameters: CreateSafeZoneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SafeZoneResponseDto> {
        const response = await this.createSafeZoneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteSafeZone without sending the request
     */
    async deleteSafeZoneRequestOpts(requestParameters: DeleteSafeZoneRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['petId'] == null) {
            throw new runtime.RequiredError(
                'petId',
                'Required parameter "petId" was null or undefined when calling deleteSafeZone().'
            );
        }

        if (requestParameters['zoneId'] == null) {
            throw new runtime.RequiredError(
                'zoneId',
                'Required parameter "zoneId" was null or undefined when calling deleteSafeZone().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/pets/{petId}/safe-zones/{zoneId}`;
        urlPath = urlPath.replace(`{${"petId"}}`, encodeURIComponent(String(requestParameters['petId'])));
        urlPath = urlPath.replace(`{${"zoneId"}}`, encodeURIComponent(String(requestParameters['zoneId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async deleteSafeZoneRaw(requestParameters: DeleteSafeZoneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseDto>> {
        const requestOptions = await this.deleteSafeZoneRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async deleteSafeZone(requestParameters: DeleteSafeZoneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseDto> {
        const response = await this.deleteSafeZoneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSafeZoneById1 without sending the request
     */
    async getSafeZoneById1RequestOpts(requestParameters: GetSafeZoneById1Request): Promise<runtime.RequestOpts> {
        if (requestParameters['petId'] == null) {
            throw new runtime.RequiredError(
                'petId',
                'Required parameter "petId" was null or undefined when calling getSafeZoneById1().'
            );
        }

        if (requestParameters['zoneId'] == null) {
            throw new runtime.RequiredError(
                'zoneId',
                'Required parameter "zoneId" was null or undefined when calling getSafeZoneById1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/pets/{petId}/safe-zones/{zoneId}`;
        urlPath = urlPath.replace(`{${"petId"}}`, encodeURIComponent(String(requestParameters['petId'])));
        urlPath = urlPath.replace(`{${"zoneId"}}`, encodeURIComponent(String(requestParameters['zoneId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getSafeZoneById1Raw(requestParameters: GetSafeZoneById1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SafeZoneResponseDto>> {
        const requestOptions = await this.getSafeZoneById1RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SafeZoneResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async getSafeZoneById1(requestParameters: GetSafeZoneById1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SafeZoneResponseDto> {
        const response = await this.getSafeZoneById1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSafeZones1 without sending the request
     */
    async getSafeZones1RequestOpts(requestParameters: GetSafeZones1Request): Promise<runtime.RequestOpts> {
        if (requestParameters['petId'] == null) {
            throw new runtime.RequiredError(
                'petId',
                'Required parameter "petId" was null or undefined when calling getSafeZones1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/pets/{petId}/safe-zones`;
        urlPath = urlPath.replace(`{${"petId"}}`, encodeURIComponent(String(requestParameters['petId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getSafeZones1Raw(requestParameters: GetSafeZones1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SafeZoneResponseDto>>> {
        const requestOptions = await this.getSafeZones1RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SafeZoneResponseDtoFromJSON));
    }

    /**
     */
    async getSafeZones1(requestParameters: GetSafeZones1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SafeZoneResponseDto>> {
        const response = await this.getSafeZones1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateSafeZone without sending the request
     */
    async updateSafeZoneRequestOpts(requestParameters: UpdateSafeZoneRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['petId'] == null) {
            throw new runtime.RequiredError(
                'petId',
                'Required parameter "petId" was null or undefined when calling updateSafeZone().'
            );
        }

        if (requestParameters['zoneId'] == null) {
            throw new runtime.RequiredError(
                'zoneId',
                'Required parameter "zoneId" was null or undefined when calling updateSafeZone().'
            );
        }

        if (requestParameters['safeZoneRequestDto'] == null) {
            throw new runtime.RequiredError(
                'safeZoneRequestDto',
                'Required parameter "safeZoneRequestDto" was null or undefined when calling updateSafeZone().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/pets/{petId}/safe-zones/{zoneId}`;
        urlPath = urlPath.replace(`{${"petId"}}`, encodeURIComponent(String(requestParameters['petId'])));
        urlPath = urlPath.replace(`{${"zoneId"}}`, encodeURIComponent(String(requestParameters['zoneId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SafeZoneRequestDtoToJSON(requestParameters['safeZoneRequestDto']),
        };
    }

    /**
     */
    async updateSafeZoneRaw(requestParameters: UpdateSafeZoneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SafeZoneResponseDto>> {
        const requestOptions = await this.updateSafeZoneRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SafeZoneResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async updateSafeZone(requestParameters: UpdateSafeZoneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SafeZoneResponseDto> {
        const response = await this.updateSafeZoneRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
