/* tslint:disable */
/* eslint-disable */
/**
 * PawGuardian API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiResponseDto,
  PetSpecies,
  SpeciesRequestDto,
} from '../models/index';
import {
    ApiResponseDtoFromJSON,
    ApiResponseDtoToJSON,
    PetSpeciesFromJSON,
    PetSpeciesToJSON,
    SpeciesRequestDtoFromJSON,
    SpeciesRequestDtoToJSON,
} from '../models/index';

export interface AddSpeciesRequest {
    speciesRequestDto: SpeciesRequestDto;
}

export interface DeleteSpeciesRequest {
    speciesId: number;
}

/**
 * 
 */
export class SpeciesControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for addSpecies without sending the request
     */
    async addSpeciesRequestOpts(requestParameters: AddSpeciesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['speciesRequestDto'] == null) {
            throw new runtime.RequiredError(
                'speciesRequestDto',
                'Required parameter "speciesRequestDto" was null or undefined when calling addSpecies().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/species`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SpeciesRequestDtoToJSON(requestParameters['speciesRequestDto']),
        };
    }

    /**
     */
    async addSpeciesRaw(requestParameters: AddSpeciesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PetSpecies>> {
        const requestOptions = await this.addSpeciesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PetSpeciesFromJSON(jsonValue));
    }

    /**
     */
    async addSpecies(requestParameters: AddSpeciesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PetSpecies> {
        const response = await this.addSpeciesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteSpecies without sending the request
     */
    async deleteSpeciesRequestOpts(requestParameters: DeleteSpeciesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['speciesId'] == null) {
            throw new runtime.RequiredError(
                'speciesId',
                'Required parameter "speciesId" was null or undefined when calling deleteSpecies().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/species/{speciesId}`;
        urlPath = urlPath.replace(`{${"speciesId"}}`, encodeURIComponent(String(requestParameters['speciesId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async deleteSpeciesRaw(requestParameters: DeleteSpeciesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseDto>> {
        const requestOptions = await this.deleteSpeciesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async deleteSpecies(requestParameters: DeleteSpeciesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseDto> {
        const response = await this.deleteSpeciesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAllSpecies without sending the request
     */
    async getAllSpeciesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/species`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getAllSpeciesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PetSpecies>>> {
        const requestOptions = await this.getAllSpeciesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PetSpeciesFromJSON));
    }

    /**
     */
    async getAllSpecies(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PetSpecies>> {
        const response = await this.getAllSpeciesRaw(initOverrides);
        return await response.value();
    }

}
