/* tslint:disable */
/* eslint-disable */
/**
 * PawGuardian API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiResponseDto,
  HealthMetricDto,
} from '../models/index';
import {
    ApiResponseDtoFromJSON,
    ApiResponseDtoToJSON,
    HealthMetricDtoFromJSON,
    HealthMetricDtoToJSON,
} from '../models/index';

export interface GetCurrentStatus1Request {
    petId: number;
}

export interface GetHistoryRequest {
    petId: number;
}

export interface RecordTelemetryRequest {
    healthMetricDto: HealthMetricDto;
}

/**
 * 
 */
export class TelemetryControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for getCurrentStatus1 without sending the request
     */
    async getCurrentStatus1RequestOpts(requestParameters: GetCurrentStatus1Request): Promise<runtime.RequestOpts> {
        if (requestParameters['petId'] == null) {
            throw new runtime.RequiredError(
                'petId',
                'Required parameter "petId" was null or undefined when calling getCurrentStatus1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/telemetry/{petId}/current`;
        urlPath = urlPath.replace(`{${"petId"}}`, encodeURIComponent(String(requestParameters['petId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getCurrentStatus1Raw(requestParameters: GetCurrentStatus1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthMetricDto>> {
        const requestOptions = await this.getCurrentStatus1RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthMetricDtoFromJSON(jsonValue));
    }

    /**
     */
    async getCurrentStatus1(requestParameters: GetCurrentStatus1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthMetricDto> {
        const response = await this.getCurrentStatus1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getHistory without sending the request
     */
    async getHistoryRequestOpts(requestParameters: GetHistoryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['petId'] == null) {
            throw new runtime.RequiredError(
                'petId',
                'Required parameter "petId" was null or undefined when calling getHistory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/telemetry/{petId}/history`;
        urlPath = urlPath.replace(`{${"petId"}}`, encodeURIComponent(String(requestParameters['petId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getHistoryRaw(requestParameters: GetHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<HealthMetricDto>>> {
        const requestOptions = await this.getHistoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(HealthMetricDtoFromJSON));
    }

    /**
     */
    async getHistory(requestParameters: GetHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<HealthMetricDto>> {
        const response = await this.getHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for recordTelemetry without sending the request
     */
    async recordTelemetryRequestOpts(requestParameters: RecordTelemetryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['healthMetricDto'] == null) {
            throw new runtime.RequiredError(
                'healthMetricDto',
                'Required parameter "healthMetricDto" was null or undefined when calling recordTelemetry().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/telemetry/record`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: HealthMetricDtoToJSON(requestParameters['healthMetricDto']),
        };
    }

    /**
     */
    async recordTelemetryRaw(requestParameters: RecordTelemetryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseDto>> {
        const requestOptions = await this.recordTelemetryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async recordTelemetry(requestParameters: RecordTelemetryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseDto> {
        const response = await this.recordTelemetryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
