/* tslint:disable */
/* eslint-disable */
/**
 * PawGuardian API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HealthMetricDto,
  PetResponseDto,
  SafeZoneResponseDto,
} from '../models/index';
import {
    HealthMetricDtoFromJSON,
    HealthMetricDtoToJSON,
    PetResponseDtoFromJSON,
    PetResponseDtoToJSON,
    SafeZoneResponseDtoFromJSON,
    SafeZoneResponseDtoToJSON,
} from '../models/index';

export interface GetCurrentStatusRequest {
    petId: number;
}

export interface GetHealthHistoryRequest {
    petId: number;
}

export interface GetPatientByIdRequest {
    petId: number;
}

export interface GetSafeZoneByIdRequest {
    petId: number;
    zoneId: number;
}

export interface GetSafeZonesRequest {
    petId: number;
}

/**
 * 
 */
export class VetControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for getCurrentStatus without sending the request
     */
    async getCurrentStatusRequestOpts(requestParameters: GetCurrentStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['petId'] == null) {
            throw new runtime.RequiredError(
                'petId',
                'Required parameter "petId" was null or undefined when calling getCurrentStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/vet/patients/{petId}/health/current`;
        urlPath = urlPath.replace(`{${"petId"}}`, encodeURIComponent(String(requestParameters['petId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getCurrentStatusRaw(requestParameters: GetCurrentStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthMetricDto>> {
        const requestOptions = await this.getCurrentStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthMetricDtoFromJSON(jsonValue));
    }

    /**
     */
    async getCurrentStatus(requestParameters: GetCurrentStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthMetricDto> {
        const response = await this.getCurrentStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getHealthHistory without sending the request
     */
    async getHealthHistoryRequestOpts(requestParameters: GetHealthHistoryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['petId'] == null) {
            throw new runtime.RequiredError(
                'petId',
                'Required parameter "petId" was null or undefined when calling getHealthHistory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/vet/patients/{petId}/health/history`;
        urlPath = urlPath.replace(`{${"petId"}}`, encodeURIComponent(String(requestParameters['petId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getHealthHistoryRaw(requestParameters: GetHealthHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<HealthMetricDto>>> {
        const requestOptions = await this.getHealthHistoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(HealthMetricDtoFromJSON));
    }

    /**
     */
    async getHealthHistory(requestParameters: GetHealthHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<HealthMetricDto>> {
        const response = await this.getHealthHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMyPatients without sending the request
     */
    async getMyPatientsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/vet/patients`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getMyPatientsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PetResponseDto>>> {
        const requestOptions = await this.getMyPatientsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PetResponseDtoFromJSON));
    }

    /**
     */
    async getMyPatients(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PetResponseDto>> {
        const response = await this.getMyPatientsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPatientById without sending the request
     */
    async getPatientByIdRequestOpts(requestParameters: GetPatientByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['petId'] == null) {
            throw new runtime.RequiredError(
                'petId',
                'Required parameter "petId" was null or undefined when calling getPatientById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/vet/patients/{petId}`;
        urlPath = urlPath.replace(`{${"petId"}}`, encodeURIComponent(String(requestParameters['petId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getPatientByIdRaw(requestParameters: GetPatientByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PetResponseDto>> {
        const requestOptions = await this.getPatientByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PetResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async getPatientById(requestParameters: GetPatientByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PetResponseDto> {
        const response = await this.getPatientByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSafeZoneById without sending the request
     */
    async getSafeZoneByIdRequestOpts(requestParameters: GetSafeZoneByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['petId'] == null) {
            throw new runtime.RequiredError(
                'petId',
                'Required parameter "petId" was null or undefined when calling getSafeZoneById().'
            );
        }

        if (requestParameters['zoneId'] == null) {
            throw new runtime.RequiredError(
                'zoneId',
                'Required parameter "zoneId" was null or undefined when calling getSafeZoneById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/vet/patients/{petId}/safe-zones/{zoneId}`;
        urlPath = urlPath.replace(`{${"petId"}}`, encodeURIComponent(String(requestParameters['petId'])));
        urlPath = urlPath.replace(`{${"zoneId"}}`, encodeURIComponent(String(requestParameters['zoneId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getSafeZoneByIdRaw(requestParameters: GetSafeZoneByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SafeZoneResponseDto>> {
        const requestOptions = await this.getSafeZoneByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SafeZoneResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async getSafeZoneById(requestParameters: GetSafeZoneByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SafeZoneResponseDto> {
        const response = await this.getSafeZoneByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSafeZones without sending the request
     */
    async getSafeZonesRequestOpts(requestParameters: GetSafeZonesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['petId'] == null) {
            throw new runtime.RequiredError(
                'petId',
                'Required parameter "petId" was null or undefined when calling getSafeZones().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/vet/patients/{petId}/safe-zones`;
        urlPath = urlPath.replace(`{${"petId"}}`, encodeURIComponent(String(requestParameters['petId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getSafeZonesRaw(requestParameters: GetSafeZonesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SafeZoneResponseDto>>> {
        const requestOptions = await this.getSafeZonesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SafeZoneResponseDtoFromJSON));
    }

    /**
     */
    async getSafeZones(requestParameters: GetSafeZonesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SafeZoneResponseDto>> {
        const response = await this.getSafeZonesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
